# Generated by Django 5.2.10 on 2026-01-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
